export const CREATENEWDEFECTSTATUS = "CREATENEWDEFECTSTATUS";
export const EDITDEFECTSTATUS = "EDITDEFECTSTATUS";

export const GETDEFECTSTATUS = "GETDEFECTSTATUS";

export const DELETEDEFECTSTATUS = "DELETEDEFECTSTATUS";
export const ERRORMESSAGE = "ERRORMESSAGE";
export const GETPDEFECTSTATUSBYID = "GETPDEFECTSTATUSBYID";