export const CREATENEWCOMPANY = 'CREATENEWCOMPANY';
export const EDITCOMPANY = 'EDITCOMPANY';
export const GETCOMPANY = 'GETCOMPANY';
export const DELETECOMPANY = 'DELETECOMPANY';
export const SHOWERRORMESSAGE = "SHOWERRORMESSAGE";

