export const CREATENEWDEFECTTYPE = 'CREATENEWDEFECTTYPE';
export const EDITDEFECTTYPE = "EDITDEFECTTYPE";

export const GETDEFECTTYPE = "GETDEFECTTYPE";

export const DELETEDEFECTTYPE = "DELETEDEFECTTYPE";
export const ERRORMESSAGE = "ERRORMESSAGE";
export const GETPDEFECTTYPEBYID = "GETPDEFECTTYPEBYID";