export const CREATEDESIGNATION="CREATEDESIGNATION";
export const UPDATEDESIGNATION="UPDATEDESIGNATION";
export const DELETEDESIGNATION="DELETEDESIGNATION";
export const GETDESIGNATION="GETDESIGNATION";
export const ERRORMESSAGE="ERRORMESSAGE";
export const GETDESIGNATIONBYID="GETDESIGNATIONBYID";
