export const ADDEMPLOYEE = 'ADDEMPLOYEE';
export const EDITEMPLOYEE = 'EDITEMPLOYEE';
export const DELETEEMPLOYEE = 'DELETEEMPLOYEE';
export const GETEMPLOYEE = 'GETEMPLOYEE';
export const SHOWERROREMESSAGE = 'SHOWERROREMESSAGE';
