//export const CREATEPRIORITY = "CREATEPRIORITY";
export const ADDPRIORITY = "ADDPRIORITY";
export const EDITPRIORITY = "EDITPRIORITY";
export const DELETEPRIORITY = "DELETEPRIORITY";
export const GETPRIORITY = "GETPRIORITY";
export const SHOWERRORMESSAGE = "SHOWERRORMESSAGE";
