export const CHANGE_INPUT_BASIC_INFO = 'CHANGE_INPUT_BASIC_INFO';
export const CHNAGE_INPUT_CHANGE_PASSWORD = 'CHNAGE_INPUT_CHANGE_PASSWORD';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';