export const IMAGE_UPLOAD_INPUT_CHANGE = 'IMAGE_UPLOAD_INPUT_CHANGE';
export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';

export const PASSWORD_INFO_INPUT_CHANGE = 'PASSWORD_INFO_INPUT_CHANGE';
export const PASSWORD_INFO_UPDATE = 'PASSWORD_INFO_UPDATE';

export const BASIC_INFO_INPUT_CHANGE = 'BASIC_INFO_INPUT_CHANGE';
export const BASIC_INFO_UPDATE = 'BASIC_INFO_UPDATE';