export const AVATAR_UPLOAD_INPUT_CHANGE = 'AVATAR_UPLOAD_CHANGE';
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';

export const TAKE_PHOTO = 'TAKE_PHOTO';

export const BASIC_INFO_INPUT_CHANGE = 'BASIC_INFO_INPUT_CHANGE';
export const UPDATE_BASIC_INFO = 'UPDATE_BASIC_INFO';

export const CHANGE_PASSWORD_INPUT_CHANGE = 'CHANGE_PASSWORD_INPUT_CHANGE';
export const UPDATE_PASSWORD_INFO = 'UPDATE_PASSWORD_INFO';