export const CREATENEWPROJECT = "CREATENEWPROJECT";
export const GETPROJECT = "GETPROJECT";
export const UPDATEPROJECT = "UPDATEPROJECT";

export const DELETEPROJECT = "DELETEPROJECT";
export const ERRORMESSAGE = "ERRORMESSAGE";
export const GETPROJECTBYID = "GETPROJECTBYID";
