export const ADDSERVERITY = "ADDSERVERITY";
export const EDITSERVERITY= "EDITSERVERITY";
export const DELETESERVERITY = "DELETESERVERITY";
export const GETSERVERITY = "GETSERVERITY";
export const SHOWERRORMESSAGE = "SHOWERRORMESSAGE";