export const SYSTEM_LOGO_CHANGE = "SYSTEM_LOGO_CHANGE";
export const SHOW_ON_DASHBOARD_SIDEBAR = "SHOW_ON_DASHBOARD_SIDEBAR";
export const FAVICON_CHANGE = "FAVICON_CHANGE";
export const SIDEBAR_COLOR = "SIDEBAR_COLOR";
export const THEME_IMAGE = "THEME_IMAGE";
