export const SYSTEM_LOGO_CHANGE = "SYSTEM_LOGO_CHANGE";
export const SHOW_ON_DASHBOARD_SIDEBAR = "SHOW_ON_DASHBOARD_SIDEBAR";
export const FAVICON_CHANGE = "FAVICON_CHANGE";
export const SIDEBAR_COLOR = "SIDEBAR_COLOR";
export const TIME_FORMAT = "TIME_FORMAT";
export const DATE_FORMAT = "DATE_FORMAT";
export const DAY_FORMAT = "DAY_FORMAT";
export const THEME_IMAGE = "THEME_IMAGE";


